# Generated by Django 5.2.4 on 2025-07-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubitemAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitens', to='core.categoriaatividade')),
            ],
            options={
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tempo_estimado', models.CharField(blank=True, help_text='Exemplo: 1 dia, 2 horas', max_length=50)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.subitematividade')),
            ],
            options={
                'unique_together': {('subitem', 'nome', 'tempo_estimado')},
            },
        ),
    ]
