# Generated by Django 5.2.4 on 2025-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaatividade_subitematividade_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=20, verbose_name='Sigla Resumida')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('tipo_empresa', models.CharField(choices=[('Terceiro Setor Sem Fins Lucrativos', 'Terceiro Setor Sem Fins Lucrativos'), ('Empresas Com Fins Lucrativos', 'Empresas Com Fins Lucrativos'), ('Clube de Futebol', 'Clube de Futebol'), ('Estatais', 'Estatais'), ('Estatais em Liquidação', 'Estatais em Liquidação'), ('Condominio', 'Condomínio')], max_length=50)),
                ('interesse_publico', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
            ],
        ),
    ]
