# Generated by Django 5.2.4 on 2025-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Sigla'),
        ),
    ]
