# Generated by Django 5.2.4 on 2025-07-23 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, choices=[('1º Trimestre', '1º Trimestre'), ('2º Trimestre', '2º Trimestre'), ('3º Trimestre', '3º Trimestre'), ('4º Trimestre', '4º Trimestre')], max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('prazo', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em Execução', 'Em Execução'), ('Concluso', 'Concluso'), ('N/A', 'N/A')], default='Não Iniciado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.atividade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriaatividade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_empresas', to='core.empresa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_empresas', to='core.exercicio')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subitematividade')),
                ('usuario', models.ForeignKey(db_column='usuario_sigla', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='sigla', verbose_name='Responsável (Sigla do Usuário)')),
            ],
        ),
    ]
