# Generated by Django 5.2.4 on 2025-07-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividadeempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_empresa', to='core.empresa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_exercicio', to='core.exercicio')),
            ],
            options={
                'verbose_name': 'Empresa Importada no Exercício',
                'verbose_name_plural': 'Empresas Importadas nos Exercícios',
                'unique_together': {('exercicio', 'empresa')},
            },
        ),
    ]
