"""
Django settings for work7 project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-d+sh0_9+%0%h4c@12mzu9-*d+q2lkq@*ce3wz&c=!59zxes75v'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'core',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'work7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Se quiser templates globais, descomente a linha abaixo e crie uma pasta 'templates' na raiz
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'work7.wsgi.application'

# Conexão com MySQL conforme seus dados
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'auditpro',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '3308',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core', 'static')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sessão permanece ativa mesmo se fechar a aba (não expira ao fechar o navegador)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7      # 7 dias, pode aumentar se quiser
SESSION_EXPIRE_AT_BROWSER_CLOSE = False    # Não expira ao fechar navegador
SESSION_SAVE_EVERY_REQUEST = True          # Renova o tempo a cada ação do usuário

AUTH_USER_MODEL = 'core.CustomUser'

LOGIN_URL = '/login/'
